# Generated by Django 4.2.23 on 2025-11-27 08:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_alter_asset_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='primary_user',
            field=models.ForeignKey(blank=True, help_text='The primary user of this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_assets', to=settings.AUTH_USER_MODEL),
        ),
    ]
