# Generated by Django 4.2.23 on 2025-11-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, default='HK', max_length=10, null=True),
        ),
    ]
