# Generated by Django 4.2.23 on 2025-11-26 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_region'),
    ]

    operations = [
    ]
