# Generated by Django 4.2.23 on 2025-11-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20251126_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('operator', 'Asset Operator'), ('approver', 'Movement Approver'), ('admin', 'Asset Administrator')], default='operator', max_length=20),
        ),
    ]
