# Generated by Django 4.2.23 on 2025-11-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_update_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('operator', 'Asset Operator'), ('approver', 'Movement Approver'), ('admin', 'Asset Administrator')], default='viewer', max_length=20),
        ),
    ]
