# Generated by Django 4.2.23 on 2025-11-27 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_viewer_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('asset_create', 'Asset Created'), ('asset_update', 'Asset Updated'), ('asset_delete', 'Asset Deleted'), ('movement_create', 'Movement Created'), ('movement_update', 'Movement Updated'), ('movement_approve', 'Movement Approved'), ('bulk_movement_create', 'Bulk Movement Created'), ('bulk_movement_update', 'Bulk Movement Updated'), ('bulk_movement_approve', 'Bulk Movement Approved'), ('stock_take_create', 'Stock Take Created'), ('stock_take_update', 'Stock Take Updated'), ('other', 'Other Action')], max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('target_model', models.CharField(blank=True, max_length=100, null=True)),
                ('target_id', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='accounts_ac_created_91b66e_idx'), models.Index(fields=['user'], name='accounts_ac_user_id_ce7693_idx'), models.Index(fields=['action_type'], name='accounts_ac_action__d504cb_idx')],
            },
        ),
    ]
