"""
Django settings for asset_tracker project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='b1928=0xp)8@1(zk&3yz-cell6+%g5!li%b!-5$ejk^a9@hm(p')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=lambda v: [s.strip() for s in v.split(',')])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'django_bootstrap5',
    'corsheaders',

    # Local apps
    'accounts',
    'assets',
    'locations',
    'movements',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'asset_tracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.sso_settings',
            ],
        },
    },
]

WSGI_APPLICATION = 'asset_tracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Cross-platform database configuration
if config('DB_NAME', default=None):
    # Production PostgreSQL configuration
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('DB_NAME'),
            'USER': config('DB_USER'),
            'PASSWORD': config('DB_PASSWORD'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='5432'),
            'OPTIONS': {
                'connect_timeout': 10,
            }
        }
    }
else:
    # Development SQLite configuration (cross-platform)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = config('TIME_ZONE', default='Asia/Hong_Kong')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication
AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'dashboard:index'
LOGOUT_REDIRECT_URL = 'accounts:login'

# Crispy Forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Bootstrap5
BOOTSTRAP5 = {
    'css_url': 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css',
    'javascript_url': 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js',
}

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'same-origin'

# Production security settings (uncomment for HTTPS deployment)
# SECURE_SSL_REDIRECT = True
# SECURE_HSTS_SECONDS = 31536000
# SECURE_HSTS_INCLUDE_SUBDOMAINS = True
# SECURE_HSTS_PRELOAD = True
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True

# Email Configuration
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
    EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
    EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')

# Logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'asset_tracker': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# ========================================
# SSO Configuration
# ========================================

# SSO General Settings
SSO_ENABLED = config('SSO_ENABLED', default=False, cast=bool)
SSO_TYPE = config('SSO_TYPE', default='SAML')  # SAML, OAUTH, or LDAP
ALLOW_LOCAL_AUTH = config('ALLOW_LOCAL_AUTH', default=True, cast=bool)
SSO_UPDATE_USER_DATA = config('SSO_UPDATE_USER_DATA', default=True, cast=bool)
SSO_JIT_PROVISIONING = config('SSO_JIT_PROVISIONING', default=True, cast=bool)
SSO_CREATE_UNKNOWN_USER = config('SSO_CREATE_UNKNOWN_USER', default=True, cast=bool)

# Site URL for SSO callbacks
SITE_URL = config('SITE_URL', default='http://localhost:8000')

# Authentication Backends
AUTHENTICATION_BACKENDS = ['django.contrib.auth.backends.ModelBackend']

if SSO_ENABLED:
    if SSO_TYPE == 'SAML':
        AUTHENTICATION_BACKENDS.insert(0, 'accounts.sso_backends.SAMLBackend')

        # SAML Configuration
        SAML_ENABLED = True
        SAML_ENTITY_ID = config('SAML_ENTITY_ID', default='')
        SAML_IDP_ENTITY_ID = config('SAML_IDP_ENTITY_ID', default='')
        SAML_SSO_URL = config('SAML_SSO_URL', default='')
        SAML_SLO_URL = config('SAML_SLO_URL', default='')
        SAML_X509_CERT = config('SAML_X509_CERT', default='')

        # SAML Attribute Mapping
        SAML_ATTRIBUTE_MAPPING_EMAIL = config('SAML_ATTRIBUTE_MAPPING_EMAIL', default='email')
        SAML_ATTRIBUTE_MAPPING_USERNAME = config('SAML_ATTRIBUTE_MAPPING_USERNAME', default='username')
        SAML_ATTRIBUTE_MAPPING_FIRST_NAME = config('SAML_ATTRIBUTE_MAPPING_FIRST_NAME', default='firstName')
        SAML_ATTRIBUTE_MAPPING_LAST_NAME = config('SAML_ATTRIBUTE_MAPPING_LAST_NAME', default='lastName')

    elif SSO_TYPE == 'OAUTH':
        AUTHENTICATION_BACKENDS.insert(0, 'accounts.sso_backends.OAuthBackend')

        # OAuth Configuration
        OAUTH_ENABLED = config('OAUTH_ENABLED', default=False, cast=bool)
        OAUTH_PROVIDER = config('OAUTH_PROVIDER', default='')
        OAUTH_CLIENT_ID = config('OAUTH_CLIENT_ID', default='')
        OAUTH_CLIENT_SECRET = config('OAUTH_CLIENT_SECRET', default='')
        OAUTH_AUTHORIZATION_URL = config('OAUTH_AUTHORIZATION_URL', default='')
        OAUTH_TOKEN_URL = config('OAUTH_TOKEN_URL', default='')
        OAUTH_USERINFO_URL = config('OAUTH_USERINFO_URL', default='')
        OAUTH_SCOPE = config('OAUTH_SCOPE', default='openid profile email')
        OAUTH_REDIRECT_URI = config('OAUTH_REDIRECT_URI', default='')

    elif SSO_TYPE == 'LDAP':
        try:
            import ldap
            from django_auth_ldap.config import LDAPSearch, GroupOfNamesType

            AUTHENTICATION_BACKENDS.insert(0, 'accounts.sso_backends.LDAPBackend')

            # LDAP Configuration
            LDAP_ENABLED = config('LDAP_ENABLED', default=False, cast=bool)
            AUTH_LDAP_SERVER_URI = config('LDAP_SERVER_URI', default='')
            AUTH_LDAP_BIND_DN = config('LDAP_BIND_DN', default='')
            AUTH_LDAP_BIND_PASSWORD = config('LDAP_BIND_PASSWORD', default='')

            # User Search
            AUTH_LDAP_USER_SEARCH = LDAPSearch(
                config('LDAP_USER_SEARCH_BASE', default=''),
                ldap.SCOPE_SUBTREE,
                config('LDAP_USER_SEARCH_FILTER', default='(sAMAccountName=%(user)s)')
            )

            # User Attribute Mapping
            AUTH_LDAP_USER_ATTR_MAP = {
                'first_name': config('LDAP_ATTR_FIRST_NAME', default='givenName'),
                'last_name': config('LDAP_ATTR_LAST_NAME', default='sn'),
                'email': config('LDAP_ATTR_EMAIL', default='mail'),
            }

            # Group Search (optional)
            if config('LDAP_GROUP_SEARCH_BASE', default=''):
                AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
                    config('LDAP_GROUP_SEARCH_BASE', default=''),
                    ldap.SCOPE_SUBTREE,
                    "(objectClass=group)"
                )
                AUTH_LDAP_GROUP_TYPE = GroupOfNamesType()

            # TLS/SSL Settings
            AUTH_LDAP_START_TLS = config('LDAP_USE_TLS', default=False, cast=bool)

            # Always update user on login
            AUTH_LDAP_ALWAYS_UPDATE_USER = True

        except ImportError:
            pass  # LDAP libraries not installed

# Role Mapping Configuration
SSO_ROLE_MAPPING_ENABLED = config('SSO_ROLE_MAPPING_ENABLED', default=False, cast=bool)
SSO_ADMIN_GROUPS = config('SSO_ADMIN_GROUPS', default='')
SSO_MANAGER_GROUPS = config('SSO_MANAGER_GROUPS', default='')
SSO_STAFF_GROUPS = config('SSO_STAFF_GROUPS', default='')
SSO_DEFAULT_ROLE = config('SSO_DEFAULT_ROLE', default='personnel')

# CORS Configuration for SSO
if SSO_ENABLED:
    CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default='', cast=lambda v: [s.strip() for s in v.split(',') if s.strip()])
    CORS_ALLOW_CREDENTIALS = True

# WhiteNoise for static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
